name: Build & Analyze with Microwalk

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

env:
  script_directory: microwalk
  # We need to do this here in order to catch the runner's repo path
  # See https://github.com/actions/runner/issues/728
  dwarf_path_prefix: ${{ github.workspace }}

jobs:
  build-analyze:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2

      - name: Build WolfSSL
        run: |
          sudo apt-get install -y autoconf automake libtool
          ./autogen.sh
          ./configure CFLAGS=-g
          make -j
      
      - name: Run Microwalk analysis
        id: run_microwalk
        uses: microwalk-project/microwalk-pin-action@v1
        with:
          script-directory: ${{ env.script_directory }}
          # Include both runner AND action workspace paths
          dwarf-path-prefix: ${{ env.dwarf_path_prefix }}:${{ github.workspace }}
      
      - name: Upload analysis result
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: ${{ github.workspace }}/${{ env.script_directory }}/results/report.sarif
          checkout_path: ${{ github.workspace }}
      
      - name: Archive analysis artifacts
        uses: actions/upload-artifact@v3
        with:
          name: leakage-analysis-results
          path: ${{ github.workspace }}/${{ env.script_directory }}/results